# Generated by Django 5.2 on 2025-05-11 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_nickname",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telegram_nickname",
                        message="Telegram nickname should start with @ and contain only letters, numbers and underscores.                     Length: 5-32 characters.",
                        regex="^@[A-Za-z0-9_]{4,31}$",
                    )
                ],
                verbose_name="Имя пользователя в Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chat id Telegram"
            ),
        ),
    ]
