# Generated by Django 5.2 on 2025-05-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Наименование привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "date_completion",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Дата начала выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Периодичность привычки"
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Требуется времени",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Привычка опубликована"
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
    ]
